#ifndef _FETCH_HPP_
#define _FETCH_HPP_

// Should be autogenerated

#include "json.hpp"

template <typename T>
class Promise {
  // ...

  // TODO: look up types for std::function
  template <typename U>
  Promise<U> then(std::function<T, Promise<U>> f) {
    // ...
  }
};

template <typename T>
T await(Promise<T> promise) {
  // ...
}

class Response {
  // ...

  Promise<JSON> json();
};

#endif // _FETCH_HPP_
