#ifndef _FETCH_HPP_
#define _FETCH_HPP_

// Should be autogenerated

#include "json.hpp"

// Promise.webidl
template <typename T>
class Promise {
  // ...

  template <typename U>
  Promise<U> then(std::function<U, Promise<T>> f) {
    // ...
  }
};

template <typename T>
T await(Promise<T> promise) {
  // ...
}

// Response.webidl
class Response {
  // ...

  Promise<JSON> json();
};

// Fetch.webidl
union RequestInfo {
  Request request;
  std::string string;
};
Promise<Request> fetch(RequestInfo, /*optional*/ RequestInit);

#endif // _FETCH_HPP_
